# Generated by Django 5.1.7 on 2025-06-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user1.png', upload_to='profile_pics'),
        ),
    ]
